<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PackageId>AgustinGigena.Authero</PackageId>
		<Version>0.0.1</Version>
		<Authors>Agustin Gigena</Authors>
		<Company>Agustin Gigena</Company>
		<Description>Paquete de autenticación con Firebase y Base de Datos, incluyendo generación de JWT</Description>
		<PackageTags>authentication;jwt;firebase;login;register</PackageTags>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<Title>AuthEro</Title>
		<RepositoryUrl>https://github.com/AgustinGigena1704/AuthEro</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<NeutralLanguage>es-AR</NeutralLanguage>
		<PackageRequireLicenseAcceptance>True</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.1" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.15.0" />
		<PackageReference Include="FirebaseAdmin" Version="3.4.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.1" />
		<PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
	</ItemGroup>

	<ItemGroup>
	  <Folder Include="Extensions\" />
	</ItemGroup>

</Project>